# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Escola-de-Cursos-26BE

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  migrate:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Restore dependecies
        run: dotnet restore WebApp/EscolaDeCursos.WebApp.csproj

      - name: Install Entity Framework CLI
        run: dotnet tool install --global donet-ef

      - name: Apply ORM Migrations
        env:
          SQLSERVER_CONECTIONSTRING: ${{ secrets.SQLSERVER_CONECTIONSTRING}}
        run: |
          dotnet ef database update `
          --project "WebApp/EscolaDeCursos.WebApp.csproj" `
          --configuration Release `
          --connection "$env:SQLSERVER_CONECTIONSTRING"



  deploy:
    runs-on: windows-latest
    needs: [build, migrate]
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CBE750D91EC7413D8FDAEA7D1F7CAFEC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5D56E48050E84CF1A06CC9FE70D50C0A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_25223542189D4218943200D4B3309F66 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Escola-de-Cursos-26BE'
          slot-name: 'Production'
          package: .
