# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - EscoladeCursos26

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  migrate:
      runs-on: windows-latest
      needs: build
      permissions:
        contents: read

      steps:
        - uses: actions/checkout@v4

        - name: Set up .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: "10.x"

        - name: Restore dependecies
          run: dotnet restore WebApp/EscolaDeCursos.WebApp.csproj

        - name: Install Entity Framework CLI
          run: dotnet tool install --global dotnet-ef

        - name: Apply ORM Migrations
          env:
            SQLSERVER_CONECTIONSTRING: ${{ secrets.SQLSERVER_CONECTIONSTRING}}
          run: |
            dotnet ef database update `
            --project "WebApp/EscolaDeCursos.WebApp.csproj" `
            --configuration Release `
            --connection "$env:SQLSERVER_CONECTIONSTRING"


  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_056F04C40E4642DF85705B1B801845E2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A646626578F742F3B7D913986124FAAF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_97CCBD0C287C439CAF53D9DAA608DD50 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EscoladeCursos26'
          slot-name: 'Production'
          package: .
